# Generated by Django 3.2.2 on 2021-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_pic.png', upload_to='products/'),
        ),
    ]
