# Generated by Django 3.2.2 on 2021-05-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_picture.png', upload_to='products/'),
        ),
    ]
